const $=id=>document.getElementById(id);
const DEVICE_KEY='astrift.forum.device.v1';
let device=localStorage.getItem(DEVICE_KEY);
if(!device||!/^[0-9a-f-]{36}$/i.test(device)){device=crypto.randomUUID();localStorage.setItem(DEVICE_KEY,device)}
let adminToken='',offset=0,hasMore=false;
const status=(message,error=false)=>{$('forumStatus').textContent=message;$('forumStatus').dataset.error=String(error)};
async function api(path,body){const response=await fetch('/api/forum'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error||'请求失败');return result}
function postElement(post){const article=document.createElement('article');article.className='forumPost'+(post.pinned?' pinned':'');const header=document.createElement('div');header.className='forumPostHeader';const name=document.createElement('b');name.textContent=post.name;const time=document.createElement('time');time.dateTime=new Date(post.created_at).toISOString();time.textContent=new Date(post.created_at).toLocaleString('zh-CN');header.append(name,time);if(post.pinned){const badge=document.createElement('span');badge.className='pinBadge';badge.textContent='置顶';header.append(badge)}const body=document.createElement('p');body.textContent=post.body;article.append(header,body);if(adminToken){const actions=document.createElement('div');actions.className='forumPostActions';const pin=document.createElement('button');pin.type='button';pin.textContent=post.pinned?'取消置顶':'置顶';pin.onclick=()=>moderate(post.id,post.pinned?'unpin':'pin');const remove=document.createElement('button');remove.type='button';remove.className='delete';remove.textContent='删除';remove.onclick=()=>{if(confirm('确定删除这条帖子？'))moderate(post.id,'delete')};actions.append(pin,remove);article.append(actions)}return article}
async function load(reset=true){try{if(reset){offset=0;$('forumPosts').replaceChildren()}const result=await api(`?offset=${offset}`);for(const post of result.posts)$('forumPosts').append(postElement(post));offset+=result.posts.length;hasMore=result.hasMore;$('forumMore').hidden=!hasMore;if(offset===0){const empty=document.createElement('p');empty.className='forumEmpty';empty.textContent='还没有帖子，来发第一条吧。';$('forumPosts').append(empty)}}catch(error){status(error.message,true)}}
async function moderate(id,action){try{await api('/moderate',{id,action,token:adminToken});status(action==='delete'?'帖子已删除':action==='pin'?'帖子已置顶':'已取消置顶');await load()}catch(error){status(error.message,true)}}
function setAdmin(active){$('forumAdminState').hidden=!active;$('forumPinWrap').hidden=!active;$('forumLogin').hidden=true;$('forumPassword').value='';$('forumAdmin').textContent=active?'管理员已登录':'管理员'}
async function logout(){const token=adminToken;adminToken='';setAdmin(false);if(token)try{await api('/logout',{token})}catch{}await load()}
$('forumBody').addEventListener('input',()=>{const chars=Array.from($('forumBody').value);if(chars.length>200)$('forumBody').value=chars.slice(0,200).join('');$('forumCount').textContent=`${Math.min(chars.length,200)} / 200`});
$('postForm').addEventListener('submit',async event=>{event.preventDefault();const button=event.submitter||$('postForm').querySelector('button[type=submit]');button.disabled=true;try{await api('/post',{name:$('forumName').value,body:$('forumBody').value,device,token:adminToken,pinned:adminToken&&$('forumPin').checked});$('forumBody').value='';$('forumPin').checked=false;$('forumCount').textContent='0 / 200';status('发布成功');await load()}catch(error){status(error.message,true)}finally{button.disabled=false}});
$('forumRefresh').onclick=()=>load();$('forumMore').onclick=()=>load(false);
$('forumAdmin').onclick=()=>{if(adminToken)return;$('forumLogin').hidden=!$('forumLogin').hidden;if(!$('forumLogin').hidden)$('forumPassword').focus()};
$('forumCancelLogin').onclick=()=>{$('forumLogin').hidden=true;$('forumPassword').value=''};
$('forumLogin').addEventListener('submit',async event=>{event.preventDefault();try{const result=await api('/login',{password:$('forumPassword').value});adminToken=result.token;setAdmin(true);status('管理员模式已开启');await load()}catch(error){status(error.message,true)}});
$('forumLogout').onclick=logout;
window.addEventListener('pagehide',()=>{if(!adminToken)return;const token=adminToken;adminToken='';navigator.sendBeacon('/api/forum/logout',new Blob([JSON.stringify({token})],{type:'application/json'}))});
void load();
