const STORAGE='astrift.skins.v1';
export const SKIN_TIERS=[
  {name:'常规',kills:10,styles:[
    {id:'glacier',name:'霜白断层',desc:'陶瓷白护板 · 冰蓝刻线',shell:0xc8dce3,dark:0x19303c,edge:0xf1fbff,grip:0x3f6170,accent:0x46d9ff},
    {id:'ember',name:'熔痕',desc:'碳黑机匣 · 赤红灼痕',shell:0x363a42,dark:0x14191f,edge:0x9e6659,grip:0x292930,accent:0xff6549},
    {id:'moss',name:'雨林幽线',desc:'消光绿装甲 · 荧绿导轨',shell:0x566c59,dark:0x172923,edge:0xb2c7a5,grip:0x334438,accent:0x88f7a4}]},
  {name:'精良',kills:50,styles:[
    {id:'nebula',name:'暮星折光',desc:'紫曜合金 · 星点导线',shell:0x51466f,dark:0x15152c,edge:0xd1b8ff,grip:0x302b4a,accent:0xc18bff},
    {id:'aurora',name:'极光切面',desc:'深海蓝钛 · 青绿棱面',shell:0x1f6475,dark:0x092b38,edge:0xb7fff3,grip:0x245463,accent:0x62ffd9},
    {id:'copper',name:'鎏金余晖',desc:'枪铜雕刻 · 熔金导槽',shell:0x72503b,dark:0x251b1c,edge:0xf0bd79,grip:0x44322e,accent:0xffd18b}]},
  {name:'传奇',kills:150,styles:[
    {id:'void',name:'蚀界·裂隙核心',desc:'黑曜浮甲 · 紫能脊刺 · 裂隙脉冲',shell:0x171b2e,dark:0x060812,edge:0x8b79c6,grip:0x1d2036,accent:0xb371ff},
    {id:'nova',name:'日冕·焚星之冠',desc:'象牙白金 · 日冕翼片 · 金焰光核',shell:0xe4d8be,dark:0x382a25,edge:0xffdf92,grip:0x776754,accent:0xffbd50},
    {id:'tide',name:'沧渊·潮汐引擎',desc:'深海钛蓝 · 环绕能流 · 青色电弧',shell:0x163d60,dark:0x071a32,edge:0x75d9ea,grip:0x23465d,accent:0x4cf5ff}]}
];
let state={kills:0,claimed:[null,null,null],active:null};
try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved&&Number.isSafeInteger(saved.kills)&&saved.kills>=0){state.kills=saved.kills;state.claimed=SKIN_TIERS.map((tier,i)=>tier.styles.some(s=>s.id===saved.claimed?.[i])?saved.claimed[i]:null);state.active=state.claimed.includes(saved.active)?saved.active:null}}catch{}
const save=()=>{try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}};
export function activeSkin(){return SKIN_TIERS.flatMap(t=>t.styles).find(s=>s.id===state.active)||null}
export function skinById(id){return SKIN_TIERS.flatMap(t=>t.styles).find(s=>s.id===id)||null}
export function applySkin(models){const skin=activeSkin(),legendary=Boolean(skin&&state.claimed[2]===skin.id);for(const model of Object.values(models)){const materials=model.userData.skinMaterials,base=model.userData.baseColors;if(!materials)continue;for(const [slot,material] of Object.entries(materials)){material.color.setHex(skin?.[slot]??base[slot]);material.metalness=skin?slot==='grip'?.3:.78:slot==='grip'?.16:.72;material.roughness=skin?slot==='grip'?.72:slot==='dark'?.42:.26:slot==='grip'?.88:.4;if(slot==='accent'){material.emissive.setHex(skin?.accent??base.accent);material.emissiveIntensity=legendary?.85:.42}}const detail=model.userData.skinDetail;if(detail){detail.group.visible=Boolean(skin);detail.legendary.visible=legendary;detail.void.visible=skin?.id==='void';detail.nova.visible=skin?.id==='nova';detail.tide.visible=skin?.id==='tide';detail.plate.color.setHex(skin?.edge??0xffffff);detail.plate.metalness=.88;detail.light.color.setHex(skin?.accent??0xffffff);detail.light.emissive.setHex(skin?.accent??0xffffff);detail.light.emissiveIntensity=legendary?1.9:.8}}}
export function updateSkinPulse(models,time){const skin=activeSkin();if(!skin||!state.claimed[2]||state.claimed[2]!==skin.id)return;const pulse=1.5+Math.sin(time*.003)*.42;for(const model of Object.values(models))if(model.userData.skinDetail)model.userData.skinDetail.light.emissiveIntensity=pulse}
export function recordKill(models){state.kills++;save();applySkin(models)}
export function initSkinScreen(models){const screen=document.getElementById('skinsScreen'),tiers=document.getElementById('skinTiers'),progress=document.getElementById('skinProgress');function render(){progress.textContent=`累计击杀 ${state.kills} 次 · 最多领取 3 套（每等级一套）`;tiers.replaceChildren();SKIN_TIERS.forEach((tier,index)=>{const section=document.createElement('section');section.className='skinsTier';const heading=document.createElement('h3');heading.textContent=`${tier.name} · ${tier.kills} 击杀`;const note=document.createElement('small');note.textContent=state.claimed[index]?'本档已领取，可切换为当前展示':state.kills>=tier.kills?'任务已完成：从三套中选定一套':'还需 '+(tier.kills-state.kills)+' 次击杀解锁';const cards=document.createElement('div');cards.className='skinCards';for(const skin of tier.styles){const button=document.createElement('button');button.type='button';button.className='skinCard';button.dataset.rarity=index===2?'legendary':index===1?'rare':'common';button.dataset.skin=skin.id;button.classList.toggle('selected',state.active===skin.id);button.disabled=state.kills<tier.kills||Boolean(state.claimed[index]&&state.claimed[index]!==skin.id);for(const slot of ['shell','dark','edge','accent'])button.style.setProperty('--'+slot,'#'+skin[slot].toString(16).padStart(6,'0'));const swatch=document.createElement('i');swatch.className='skinSwatch';for(const part of ['barrel','body','rail','stock','grip','mag','core','mark']){const piece=document.createElement('em');piece.className='skinPreview-'+part;swatch.append(piece)}const name=document.createElement('b');name.textContent=skin.name;const desc=document.createElement('small');desc.textContent=state.active===skin.id?'使用中':state.claimed[index]===skin.id?'点击使用':skin.desc;button.append(swatch,name,desc);button.onclick=()=>{if(state.kills<tier.kills||state.claimed[index]&&state.claimed[index]!==skin.id)return;if(!state.claimed[index]){if(!confirm(`确定领取「${skin.name}」？${tier.name}等级只能领取这一套。`))return;state.claimed[index]=skin.id}state.active=skin.id;save();applySkin(models);render()};cards.append(button)}section.append(heading,note,cards);tiers.append(section)})}document.getElementById('openSkins').onclick=()=>{render();screen.hidden=false};document.getElementById('closeSkins').onclick=()=>screen.hidden=true;applySkin(models);return render}
